--Up migration for 20220619191732_7_Create_Users_Table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Users')
BEGIN
	CREATE TABLE Users
	(
		Id INT IDENTITY(1,1),
		Name NVARCHAR(100) NOT NULL,
		Email NVARCHAR(200) NOT NULL,
		Password NVARCHAR(MAX) NOT NULL,
		DOB DATETIME NOT NULL,
		ProfilePicture NVARCHAR(MAX) NULL,
		CoverPicture NVARCHAR(MAX) NULL,
		About NVARCHAR(MAX) NULL,
		CreatedAt DATETIME NOT NULL,
		UpdatedAt DATETIME NULL
	)
	ALTER TABLE Users ADD CONSTRAINT CreatedAt_Users_Default DEFAULT GETDATE() FOR CreatedAt
END
